version: "3.6"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=dbTest
    ports:
      - 3309:3306
    networks:
      - internal
networks:
  internal:
    driver: bridge
